INSERT INTO open_music.artist (id, name, nickname, cover, genre, bio, created_at, deleted) VALUES (1, 'Coldplay', '酷玩乐队', '/api/file/download/9278a40e-2567-4d3f-bd83-a7574e7ae961/1681x1681.png', '另类音乐;后英式摇滚;流行;流行摇滚;另类摇滚', '木吉他与电吉他渐次铺展开温和的声音，随后引入鼓、贝斯与钢琴，在一段长达 33 秒的前奏后，Chris Martin 直抵内心的细腻假声迎面而来——2000 年，凭借一首浪漫至极的表白神曲《Yellow》问世，成立于 1996 年的英国摇滚乐队 Coldplay 迅速风靡全世界。而后《The Scientist》《Fix You》两首金曲接续诞生，画下哀伤而深刻的感情线，镌刻着早期 Coldplay 最美的声影。

Coldplay 发迹于 Britpop 浪潮骤然褪去时，曾以 Post-Britpop 的名义试图唤回 90 年代 Britpop 的往日荣光。而以第一、二张专辑连续两届拿下格莱美“最佳另类摇滚专辑”的耀眼成绩，让他们更有底气以另类的声响重新定义主流摇滚乐：在激烈喧嚣与愤世嫉俗外，摇滚乐也可以是由温暖的器乐演奏、细腻的真假声转换、旋律优美的钢琴叙事、积极向阳的主题组成的。

成军于伦敦大学学院校园内，毕业大考后，Coldplay 旋即赢得了主流大厂一纸包含五张专辑的合约，并在前三张专辑发行后向世人证明，他们在忠于自己的音乐并保持英国特色的前提下，亦可在国际市场大红大紫。从第四张专辑《Viva La Vida》引入拉丁文化、携手氛围音乐大师 Brian Eno 担纲制作人开始，Coldplay 的音乐全面走向流行化，并与国际音乐风潮接轨：吉他伴奏的比重下降、电子舞曲元素增加，几乎拿掉了细腻的假声，而以厚重而外放的低音域唱法取而代之。无论是 2011 年号称“摇滚歌剧”的《Mylo Xyloto》、2019 年贯穿折中主义的《Everyday Life》，抑或携手 The Chainsmokers、Selena Gomez、Beyoncé、BTS 防弹少年团等带来各式跨界金曲以营造体育场内声势浩大的集体狂欢，Coldplay 始终传播着至深至浓、振奋人心的力量。', '2025-05-12 00:59:12', 0);
INSERT INTO open_music.artist (id, name, nickname, cover, genre, bio, created_at, deleted) VALUES (2, 'OneRepublic', '一体共和;共和时代', '/api/file/download/9848eebc-4eb6-472a-bde6-b2042212d8fa/3840x3840cc.png', '国际流行;流行摇滚;流行乐;另类摇滚', '流行摇滚乐队 OneRepublic 不断创造金曲，从不拘泥于固定法则。这份流行直觉与创意，很大程度上来自于主唱 Ryan Tedder。1990 年代末期，Tedder 开始与高中好友一起在科罗拉多州的咖啡厅表演，其中的表演搭档 Zach Filkins 后来成为了乐队的吉他手。几年后 Tedder 搬到了洛杉矶，与 Filkins 再度聚首，于 2002 年共同组建 OneRepublic。与此同时，Tedder 还开启了音乐创作事业，为 Leona Lewis、Hilary Duff 和 Jennifer Lopez 等艺人写歌并担任制作人。但谈到自己的乐队时，他表示自己的目标从来不是写一首热门单曲，而是创造发自内心的艺术作品。

“我们的歌必须百分之百的真诚，它们来自我的人生经历。如果我没有真情实感，没有亲身经历，如果它无法让我产生共鸣，我就唱不出来。” Ryan Tedder 告诉 Apple Music。从他们 2006 年的第一首单曲《Apologize》开始（这首歌最终收获多白金销量），到之后更成功的歌，比如 2013 年冲劲十足的民谣流行单曲《Counting Stars》、2016 年有着悦耳合成器律动的《Kids》等更加多样的作品，Tedder 这种发自肺腑的创作理念，让 OneRepublic 的歌为人们带来了直抵心灵的震撼。Tedder 一面继续为 Beyoncé、Ed Sheeran 和 Adele 等超级巨星写歌与制作音乐，一面也将最具情绪冲击力的灵感，保留给 OneRepublic 下一首横扫全球的大作。', '2025-05-12 01:18:41', 0);
INSERT INTO open_music.artist (id, name, nickname, cover, genre, bio, created_at, deleted) VALUES (3, 'Imagine Dragons', '梦龙乐队', '/api/file/download/5eff1edf-f71b-46f5-b04a-681863f138b8/1486x1486cc.png', '另类音乐;另类摇滚', '2011 年，Imagine Dragons 要在拉斯维加斯的赌场里一连唱上 6 个小时，赚到的钱才刚刚够支付房租和吃快餐的开销。而一年多之后，他们已经是白金级的当红乐队了。这支由几个高中与大学时代的朋友组成的乐队，成立于犹他州的普洛佛市，在独立发行 3 张 EP 后，于 2012 年加入了 Interscope 唱片公司，并在同一年推出了首张全长专辑《Night Visions》。凭借《It’s Time》和《Radioactive》两首爆红单曲，Imagine Dragons 一跃成为了 2010 年代最引人注目的乐队之一。他们的独立摇滚气势恢宏，融合了 Synth-Pop，Dubstep、鼓点强劲的民谣与新浪潮等元素，如同亮丽霓虹般迸发出旺盛活力。接下来，他们推出多张佳作（2015 年的《Smoke + Mirrors》，2017 年的《Evolve》，2018 年的《Origins》），在不断提升音乐品质的同时，所宣泄的情绪也从未在其中被削弱。

主唱 Dan Reynolds 向 Apple Music 介绍 2018 年的单曲《Zero》时强调了同理心在创作与表演时的作用——这也是乐队成功的基石。“我以前带着一个比我个头还要大的次中音萨克斯到处表演。”他在回忆少年经历时说道，“当时我大概只有 1 米 57，是个矮小的孩子。我是经历过漫长成长阶段的，所以当我看到一些正在努力但此时还不太耀眼的人时，会想‘噢，你现在正在经历着难关，给自己点时间——总有一天你会迎来属于自己的时刻，尽情盛放的。’所以这首歌送给所有和我有过一样经历的人们。”', '2025-05-12 01:31:36', 0);
INSERT INTO open_music.artist (id, name, nickname, cover, genre, bio, created_at, deleted) VALUES (4, 'Maroon 5', '魔力红;马老五', '/api/file/download/08a46468-ed6a-4314-b3fa-55c945ad3f57/4906x4906.png', '国际流行;流行摇滚', '2004 年，Maroon 5 的歌曲《This Love》的音乐视频在 MTV 播放时，被剪掉了和性有关的用词。从某种程度上来说，这算得上是一种“接地气”的表达：已然是超级巨星的 Maroon 5，依旧保持着影响力之外的性感魅力。他们能在歌词中讨论闺房之乐，而且，他们是 21 世纪有突破性的主流乐队代表之一——既用着吉他、贝斯、鼓，又能能跟上嘻哈与电子乐的创新节奏。

2000 年代初期，乐队在洛杉矶成军，几名主要成员从高中时代就是好友。他们早年曾组建过一支名叫 Kara’s Flowers 的乐队，但那时的音乐风格同后来大相径庭， 这支乐队后来无果而终。主唱 Adam Levine 在 Maroon 5 成立那会儿刚刚开始接触嘻哈音乐文化，在此影响下，乐队 2002 年推出的专辑《Songs About Jane》虽是佳作但稍显慢热，过了大约两年时间才攀升到各大榜单的上游。此后乐队开始了频繁的巡演。在 2007 年的专辑《It Won\'t Be Soon Before Long》里，他们深入探索灵魂乐与 Prince 式的流行摇滚，2010 年的《Hands All Over》则变得更加精良，蕴含更多力量。2011 年，Levine 开始在《美国之声》节目中担任导师，这让他个人的名望再度上升，同时也进一步扩大了这支乐队的知名度。', '2025-05-12 01:44:45', 0);
INSERT INTO open_music.artist (id, name, nickname, cover, genre, bio, created_at, deleted) VALUES (5, 'LINKIN PARK', '林肯公园', '/api/file/download/f24ab5a6-1e63-4c5f-a432-1c0c535ef0ca/1486x1486.png', '硬摇滚;流行摇滚;新金属;另类摇滚;说唱摇滚;电子摇滚', '2000 年，LINKIN PARK 在创作专辑《Hybrid Theory》的歌词时，Mike Shinoda 和 Chester Bennington 就一起定下了一条规定：不许写脏字。一方面，这样是为了留住更多听众——他们的乐迷中有相当一部分是青少年，唱片上的“家长指导”标签可能会造成麻烦；另一方面，Shinoda 和 Bennington 不想用生硬的咒骂来表达沮丧，而是要挑战自己，去袒露那些会被脏字遮盖的内心伤痛。在更深层次的意义上，这个选择也为他们以隐喻宣泄情感的做法铺平道路：LINKIN PARK 心中满怀怒火，但他们把这怒火燃烧得彻底而干净。

《Hybrid Theory》是一张定义时代的专辑，很多人认为它是说唱金属与摇滚在商业与创意上的巅峰之作。但乐队之所以能持续获取成功，一部分原因还是因为他们音乐的多面性：尽管猛烈，但他们从不仅仅给人以硬朗霸气的感觉，而是用 Emo 和 Synth-Pop 的敏感细腻，改写了硬摇滚的惯有气焰。吉他部分的表达变得克制之后，他们转向更深沉的后硬核电子乐风，这让 Bennington 得以展现英国电子乐队 Depeche Mode 对自己的影响，同时不再咄咄逼人，便能表露痛苦。在 2017 年的专辑《One More Light》中，LINKIN PARK 开始走向“流行”，而此时距这支乐队重新定义商业摇滚的概念，已经过去近 20 年了。

LINKIN PARK 1996 年在洛杉矶郊成立。成军头几年，他们的事业并不顺利，唱片公司的主管一度建议他们开除 Shinoda，改走更传统的摇滚乐队路线。好在横空出世的《Hybrid Theory》成为硬摇滚的分水岭，从此人们再也无法忽视嘻哈与电子乐的影响。乐队在 2003 年推出了《Meteora》，并在接下来的 3 张专辑（2007 年的《Minutes to Midnight》、2010 年的《A Thousand Suns》和 2012 年的《LIVING THINGS》）中越来越倾向电子乐，随之而来的是 2014 年的《The Hunting Party》。2017 年，《One More Light》发行几个月后，前主唱 Chester Bennington 自杀身亡。沉寂数年后，乐队才又低调地开启了新的音乐创作。', '2025-05-12 01:55:15', 0);
INSERT INTO open_music.artist (id, name, nickname, cover, genre, bio, created_at, deleted) VALUES (6, 'The Fray', '瑕疵乐团;冲突乐队', '/api/file/download/33d147fd-5864-4d91-863e-dd79559e6698/4776x4776.png', '另类摇滚', null, '2025-05-12 02:05:19', 0);
INSERT INTO open_music.artist (id, name, nickname, cover, genre, bio, created_at, deleted) VALUES (7, 'U2', '', '/api/file/download/af4c94eb-b2ee-4ca5-a9cc-463b36dd859d/4320x2160.png', '摇滚', null, '2025-05-12 02:11:56', 0);
INSERT INTO open_music.artist (id, name, nickname, cover, genre, bio, created_at, deleted) VALUES (8, 'The Goo Goo Dolls', null, '/api/file/download/01e3b62b-e31a-45f3-8986-67e4f9de2469/4123x4123.png', '摇滚', null, '2025-05-12 02:21:11', 0);
INSERT INTO open_music.artist (id, name, nickname, cover, genre, bio, created_at, deleted) VALUES (9, 'Phillip Phillips', null, '/api/file/download/eb44d601-3ca2-413a-9666-09575be1ceb7/616x616.png', '国际流行', null, '2025-05-12 02:24:28', 0);
